import 'package:http/http.dart' as http;
import 'dart:convert';
import 'package:mobile_iot/analytics/domain/entities/event.dart';
import 'package:mobile_iot/core/config/env.dart';
import 'package:mobile_iot/shared/exceptions/session_expired_exception.dart';

/// Service class for handling event-related API operations.
/// 
/// This class provides methods for communicating with the backend API
/// to retrieve sensor event data. It handles HTTP requests, response
/// parsing, and error management for event data operations.
/// 
/// The service uses the http package for network communication and
/// includes proper error handling for authentication and network issues.
class EventApiService {
  /// The base URL for event-related API endpoints.
  /// 
  /// Constructed from the environment configuration to ensure
  /// consistency across different deployment environments.
  static final String _baseUrl = '${Env.apiUrl}${Env.eventsEndpoint}';

  /// Retrieves all events associated with a specific sensor device from the API.
  /// 
  /// This method makes an HTTP GET request to the backend API to fetch
  /// all sensor events (water readings, quality alerts, etc.) that were
  /// generated by the specified sensor device.
  /// 
  /// Parameters:
  /// - [token]: The authentication token for API access
  /// - [id]: The unique identifier of the sensor device
  /// 
  /// Returns a Future that completes with a list of Event entities.
  /// 
  /// Throws:
  /// - [SessionExpiredException] when the authentication token is invalid (401/403)
  /// - [Exception] for other network or data access errors
  Future<List<Event>> getAllEventsBySensorId(String token, int id) async {
    final response = await http.get(
      Uri.parse('$_baseUrl/sensor/$id'),
      headers: {
        'Authorization': 'Bearer $token',
        'Content-Type': 'application/json',
      },
    );
    if (response.statusCode == 200) {
      final List<dynamic> jsonList = jsonDecode(response.body);
      return jsonList.map((json) => Event.fromJson(json)).toList();
    } else {
      if (response.statusCode == 401 || response.statusCode == 403) {
        throw SessionExpiredException();
      }
      throw Exception('Failed to load events: ${response.statusCode} - ${response.reasonPhrase}');
    }
  }
}