/// Represents a report generated by a resident about water-related issues or observations.
/// 
/// This entity encapsulates information about user-generated reports,
/// including title, description, creation date, status, and associated
/// resident and provider identifiers.
/// 
/// The entity provides JSON serialization and deserialization methods
/// for API communication and report management.
class Report{

  /// The unique identifier for the report.
  final int id;
  
  /// The title or subject of the report.
  final String title;
  
  /// The detailed description of the issue or observation.
  final String description;
  
  /// The date when the report was created or emitted.
  final String emissionDate;
  
  /// The current status of the report (e.g., 'pending', 'in_progress', 'resolved').
  final String status;
  
  /// The identifier of the resident who created the report.
  final int residentId;
  
  /// The identifier of the water provider associated with the report.
  final int providerId;

  /// Creates a report with the specified parameters.
  /// 
  /// All parameters are required and represent the core data
  /// for report tracking and management.
  Report({
    required this.id,
    required this.title,
    required this.description,
    required this.emissionDate,
    required this.status,
    required this.residentId,
    required this.providerId,
  });

  /// Converts the report to a JSON map for API communication.
  /// 
  /// Returns a Map containing all report properties formatted
  /// according to the backend API specification.
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'title': title,
      'description': description,
      'emissionDate': emissionDate,
      'status': status,
      'residentId': residentId,
      'providerId': providerId,
    };
  }
  
  /// Creates a Report instance from a JSON map.
  /// 
  /// This factory constructor parses JSON data from the API,
  /// casting values to their appropriate types for report properties.
  /// 
  /// Parameters:
  /// - [json]: The JSON map containing report data
  /// 
  /// Returns a new Report instance with parsed data.
  factory Report.fromJson(Map<String, dynamic> json) {
    return Report(
      id: json['id'] as int,
      title: json['title'] as String,
      description: json['description'] as String,
      emissionDate: json['emissionDate'] as String,
      status: json['status'] as String,
      residentId: json['residentId'] as int,
      providerId: json['providerId'] as int
    );
  }
}