import 'package:mobile_iot/monitoring/domain/entities/device.dart';
import 'package:mobile_iot/monitoring/domain/entities/event.dart';

/// Abstract interface for device data operations.
/// 
/// This repository interface defines the contract for retrieving
/// device information and events from various data sources.
/// 
abstract class DeviceRepository {
  /// Retrieves events associated with a specific device.
  /// 
  /// This method fetches all events that were generated by the specified
  /// device, using the provided authentication token and device identifier.
  /// 
  /// Parameters:
  /// - [token]: The authentication token for API access
  /// - [deviceId]: The unique identifier of the device
  /// 
  /// Returns a Future that completes with a list of Event entities.
  Future<List<Event>> getEventsByDeviceId(String token, int deviceId);
}