import 'package:mobile_iot/monitoring/domain/entities/event.dart';

/// Abstract interface for event data operations.
/// 
/// This repository interface defines the contract for retrieving
/// sensor event data from various data sources. It follows the
/// repository pattern to abstract data access logic from the
/// business logic layer.
/// 
/// Implementations of this interface handle the actual data retrieval
/// from APIs, local storage, or other data sources.
abstract class EventRepository {

  /// Retrieves all events associated with a specific sensor device.
  /// 
  /// This method fetches all sensor events (water readings, quality alerts, etc.)
  /// that were generated by the specified sensor device, using the provided
  /// authentication token.
  /// 
  /// Parameters:
  /// - [token]: The authentication token for API access
  /// - [id]: The unique identifier of the sensor device
  /// 
  /// Returns a Future that completes with a list of Event entities.
  Future<List<Event>> getAllEventsBySensorId(String token, int id);
}